// Lista de produtos
const produtos = {

    //Multimídias
    "DMHG228BT": {
        nome: "Multimídia Player DMHG228BT - Pioneer",
        codigo: "1919.531.0307",
        descricao: "Com Tela De 6.2\" WVGA, Bluetooth, USB, Rádio AM/FM, Auxiliar, Entrada para Câmera de Ré.",
        marca: "Pioneer",
        categoria: "Multimídia",
        imagem: "./img/DMHG228BT_1.png",
        caracteristicas: [
           "2-DIN",
"Tela de 6.2 Polegadas Touch Screen Resistiva",
"Ligações Hands-free e streaming de áudio (Bluetooth)",
"Entrada para Câmera de Ré",
"Entrada para Comando de Volante",
"Entrada AUX",
"Integração com Smartphone (Via USB/Bluetooth)",
"Rádio AM/FM",
"2 Saídas RCA Pré-Amplificadas (2 V)",
"Reforçador de Graves (BassBoost)",
        ]
    },
    "DMHZ5380TV": {
        nome: "Multimídia player DMHZ5380TV - Pioneer",
        codigo: "1919.531.0311",
        descricao: "Multimídia Receiver com tela HD Capacitiva de 6.8 polegadas, Apple Carplay™, Android Auto™, Bluetooth®, TV Digital e muito mais!",
        marca: "Pioneer",
        categoria: "Multimídia",
        imagem: "./img/DMHZ5380TV_1.png",
        caracteristicas: [
            "2-DIN Chassi Regular",            
"Tela de 6.8 Polegadas Touch screen Capacitiva",
"TV Digital Integrada",
"Ligações Hands-free e Streaming de Áudio (Bluetooth)",
"Compatível com Apple CarPlay™",
"Compatível com Android Auto™",
"Compatível com WebLink® (iPhone/Android)",
"3 Saídas RCA Pré-amplificadas (4V)",
"Saída de Vídeo para Monitor Traseiro",
"Entrada para Câmera de Ré",
"Entrada para Controle de Volante",
        ]
    },
    "DMHA248BT": {
        nome: "Multimídia player DMHA248BT - Pioneer",
        codigo: "1919.531.0321",
        descricao: "Multimídia Receiver com Tela De 6.2 polegadas, Weblink™, Bluetooth®, USB, Rádio AM/FM, Entrada para Câmera de Ré, e muito mais!",
        marca: "Pioneer",
        categoria: "Multimídia",
        imagem: "./img/DMHA248BT_1.png",
        caracteristicas: [
            "2-DIN Chassi Curto",
"Tela de 6.2 Polegadas Touch Screen",
"Entrada para Câmera de Ré",
"Compatível com WebLink™ (iPhone/Android)",
"Bluetooth® para Ligações Hands-free e Streaming de Áudio",
"Spotify®",
"Entrada USB",
"3 Saídas RCA Pré-Amplificadas (2 V)",
"Equalizador 13 Bandas",
"Rádio AM/FM",
"Saída de Vídeo para Monitor Traseiro",
        ]
    },
    "DMHA348BT": {
        nome: "Multimídia player DMHA348BT - Pioneer",
        codigo: "1919.531.0323",
        descricao: "Multimídia Receiver com Tela Capacitiva de 6.8 Polegadas, Weblink™, Weblink Cast™, Bluetooth®, USB, Rádio AM/FM, Alta Qualidade de Áudio e muito mais!",
        marca: "Pioneer",
        categoria: "Multimídia",
        imagem: "./img/DMHA348BT_1.png",
        caracteristicas: [
            "2-DIN Chassi Curto",
"Tela de 6.8 Polegadas Touch Screen Capacitiva",
"Entrada para Câmera de Ré",
"Espelhamento e Controle de Aplicativos Compatíveis de Smartphone com WebLink™ (iPhone/Android)",
"Compatível com WebLink™ (iPhone/Android)",
"Compatível com WebLink Cast™ (iPhone/Android)",
"Bluetooth® para Ligações Hands-free e Streaming de Áudio",
"Entrada USB",
"3 Saídas RCA Pré-Amplificadas (2 V)",
"Equalizador 13 Bandas",
"Saída de Vídeo para Monitor Traseiro",
        ]
    },
      "DMHA5450BT": {
        nome: "Multimídia player DMHA5450BT - Pioneer",
        codigo: "1919.531.0324",
        descricao: "Com tela capacitiva de 6.8 polegadas, Apple Carplay®, Android Auto™, Wi-Fi®, Bluetooth®, USB, Rádio AM/FM, alta qualidade de áudio e muito mais!",
        marca: "Pioneer",
        categoria: "Multimídia",
        imagem: "./img/DMHA5450BT_1.png",
        caracteristicas: [
            "2-DIN Chassi Curto",
"Tela de 6.8 Polegadas Touch Screen Capacitiva",
"Entrada para Câmera de Ré",
"Entrada para Comando de Volante",
"Compatível com Apple CarPlay™ (Wireless/USB)",
"Compatível com Android Auto™ (Wireless/USB)",
"Compatível com Weblink®",
"Compatível USB Mirroring (Android™)",
"Compatível com Google Maps & Waze (Apple CarPlay™ / Android Auto™)",
"Bluetooth®",
"Spotify®",
"Entrada USB",
"3 Saídas RCA Pré-Amplificadas (2 V)",
"Equalizador 13 Bandas",
"Saída de Vídeo para Monitor Traseiro",
        ]
    },
       "DMHAF555BT": {
        nome: "Multimídia player DMHAF555BT - Pioneer",
        codigo: "1919.531.0326",
        descricao: "Multimídia Receiver Com Tela Flutuante De 9 Polegadas Capacitiva, Weblink™, Weblink Cast™, Bluetooth®, USB, Rádio AM/FM, alta qualidade de áudio e muito mais...",
        marca: "Pioneer",
        categoria: "Multimídia",
        imagem: "./img/DMHAF555BT_1.png",
        caracteristicas: ["2-DIN Chassi Curto",
"Tela de 6.8 Polegadas Touch Screen Capacitiva",
"Entrada para Câmera de Ré",
"Entrada para Comando de Volante",
"Compatível com Apple CarPlay™ (Wireless/USB)",
"Compatível com Android Auto™ (Wireless/USB)",
"Compatível com Weblink®",
"Compatível USB Mirroring (Android™)",
"Compatível com Google Maps & Waze (Apple CarPlay™ / Android Auto™)",
"Bluetooth®",
"Spotify®",
"Entrada USB",
"3 Saídas RCA Pré-Amplificadas (2 V)",
"Equalizador 13 Bandas",
"Saída de Vídeo para Monitor Traseiro",
        ]
    },
   
   
    "DMHZF8550TV": {
        nome: "Multimídia player DMHZF8550TV - Pioneer",
        codigo: "1919.531.0327",
        descricao: "Multimídia Receiver com Tela Flutuante de 9 Polegadas Capacitiva, Apple Carplay®, Android Auto™, WI-FI®, Bluetooth®, TV Digital, USB, Rádio AM/FM, alta qualidade de áudio e muito mais...",
        marca: "Pioneer",
        categoria: "Multimídia",
        imagem: "./img/DMHZF8550TV_1.png",
        caracteristicas: ["1-DIN",
"Tela de 9 Polegadas Touchscreen Capacitiva",
"Conexão Wi-Fi®",
"Compatível com Android Auto™",
"Compatível com Apple CarPlay™",
"Compatível com WebLink™",
"Compatibilidade com WebLink Cast™ (Espelhamento de Celular)",
"Bluetooth para Ligações Hands-free e Streaming de Áudio",
"Rádio AM/FM",
"3 Pares de Saídas RCA Pré-amplificadas",
"Saída de Vídeo para Monitor Traseiro",
"Entrada para Câmera de Ré",
"Entrada para Comando de Volante",
        ]
    },

    "DMHA5650BT": {
        nome: "Multimídia player DMHA5650BT - Pioneer",
        codigo: "1919.531.0329",
        descricao: "Multimídia Receiver Com Tela Capacitiva De 6.8 Polegadas, Wi-Fi®, Apple Carplay®, Android Auto™, Weblink™, Bluetooth®, Usb, Rádio Fm, Alta Qualidade de Áudio e muito mais...",
        marca: "Pioneer",
        categoria: "Multimídia",
        imagem: "./img/DMHA5650BT_1.png",
        caracteristicas: [ "1-DIN Chassi Curto",
"Tela WVGA de 6.8 Polegadas Touchscreen Capacitiva",
"Conexão Wi-Fi®",
"Compatível com Android Auto™ (Wi-Fi / USB)",
"Compatível com Apple CarPlay™ (Wi-Fi / USB)",
"Compatível com WebLink™/ WebLink™ Cast",
"Bluetooth para Ligações Hands-free e Streaming de Áudio",
"3 Pares de Saídas RCA Pré-amplificadas (4V)",
"Entrada para Câmera de Ré",
"Entrada para Comando de Volante",
"Saída de Vídeo para Monitor Traseiro",
        ]
    },

    //Media Players
    "MVH098UB": {
        nome: "Media Player MVH098UB - Pioneer",
        codigo: "1919.530.0255",
        descricao: "Reproduz MP3, WMA, WAV e FLAC, equalizador gráfico de 5 bandas e reforçador de graves. Banda FM estendida (76 KHz-108 KHz)",
        marca: "Pioneer",
        categoria: "Media Player",
        imagem: "./img/MVH098UB_1.png",
        caracteristicas: [ "Entrada USB frontal 1",
"Interface para AndroidTM (USB) 2",
"Reprodução de arquivos MP3, WMA, WAV, FLAC",
"Saída RCA com controle para subwoofer",
"Entrada auxiliar frontal",
        ]
    },

    "MVHS218BT": {
        nome: "Media Player MVHS218BT - Pioneer",
        codigo: "1919.530.0277",
        descricao: "Realize chamadas viva-voz e streaming de áudio através do Bluetooth®. Com entrada USB frontal, auxiliar e rádio AM/FM.",
        marca: "Pioneer",
        categoria: "Media Player",
        imagem: "./img/MVHS218BT_1.png",
        caracteristicas: [ "Tecnologia Bluetooth® (ligações telefônicas e streaming de áudio) ¹",
"Entrada USB ²",
"Entrada AUX",
"Display OFF",
"Sintonizador FM/AM",
"RDS 3 (oferece informações de texto juntamente com a recepção de FM)",
"Frente destacável",
        ]
    },

    "MVHS118UI": {
        nome: "Media Player MVHS118UI - Pioneer",
        codigo: "1919.530.0282",
        descricao: "Plugue o seu pendrive ou smartphone na entrada USB frontal e curta suas playlists favoritas.",
        marca: "Pioneer",
        categoria: "Media Player",
        imagem: "./img/MVHS118UI_1.png",
        caracteristicas: [ "Compatibilidade com Android™",
"Compatibilidade com iPhone/iPod",
"MIXTRAX",
"Compatível com Spotify™ (iPhone)",
"1 Entrada USB Frontal",
"Entrada para controle de volante",
"Equalizador 5-Bandas",
"Controle de Subwoofer",
        ]
    },
    
    "SPHC10BT": {
        nome: "Media Player SPHC10BT - Pioneer",
        codigo: "1919.530.0288",
        descricao: "Acople o seu smartphone direto no rádio do seu carro e aproveite todas as funcionalidades.",
        marca: "Pioneer",
        categoria: "Media Player",
        imagem: "./img/SPHC10BT_1.png",
        caracteristicas: [ "Ligações Hands-Free e Streaming de Áudio ¹",
"Entrada USB frontal ²",
"Compatível com aplicativo Pioneer Smart Sync ⁶",
"Equalizador Gráfico 13-bandas / Equalizador Gráfico 31-bandas (Via Pioneer Smart Sync)",
"Dynamic Bass Enhancer (Graves Super Potentes)",
"Entrada para Controle de Volante",
"3 Saídas RCA (2V)",
"Assistente de estacionamento ¹⁰",
"Botões de acesso direto a aplicativos",
"Design inovador",
        ]
    },

    "MVHX3000BR": {
        nome: "Media Player MVHX3000BR - Pioneer",
        codigo: "1919.530.0301",
        descricao: "Estilo e potência no painel do seu carro!",
        marca: "Pioneer",
        categoria: "Media Player",
        imagem: "./img/MVHX3000BR_1.png",
        caracteristicas: [ "Ligações Telefônicas e Streaming de Áudio",
"Entrada USB frontal",
"Entrada AUX",
"Entrada para Comando de Volante",
"2 Saídas Pré-Amplificadas de Áudio",
"Flashing Light (Efeitos de Iluminação)",
"Interface para Android™",
"Interface para iPhone",
"Compatível com Spotify®",
"Compatível com aplicativo PIONEER SMART SYNC",
"EQ 13-bandas / EQ Gráfico 31-bandas (Pioneer Smart Sync)",
"Função Karaoke (Vocal Cancel)",
        ]
    },

    "MVHX7000BR": {
        nome: "Media Player MVHX7000BR - Pioneer",
        codigo: "1919.530.0302",
        descricao: "O receiver mais completo da categoria para você ficar conectado.",
        marca: "Pioneer",
        categoria: "Media Player",
        imagem: "./img/MVHX7000BR_1.png",
        caracteristicas: [ "Ligações Telefônicas e Streaming de Áudio",
"Entrada USB frontal",
"Entrada AUX",
"Entrada para Comando de Volante",
"3 Saídas Pré-Amplificadas de Áudio / Hi-Volt (4V)",
"Flashing Light (Efeitos de Iluminação)",
"Interface para Android™",
"Interface para iPhone",
"Compatível com Spotify®",
"Compatível com aplicativo PIONEER SMART SYNC",
"EQ 13-bandas / EQ Gráfico 31-bandas (Pioneer Smart Sync)",
"Função Karaoke (Vocal Cancel)",
        ]
    },

     "DEHS4280BT": {
        nome: "CD Player DEHS4280BT - Pioneer",
        codigo: "1919.530.0304",
        descricao: "Conecte seu smartphone e aproveite todas as possibilidades do seu Pioneer.",
        marca: "Pioneer",
        categoria: "Media Player",
        imagem: "./img/DEHS4280BT_1.png",
        caracteristicas: [ "CD Player",
"Ligações Hands-Free e Streaming de Áudio",
"Entrada USB frontal",
"Entrada AUX",
"Entrada para Comando de Volante",
"2 Saídas Pré-Amplificadas (Áudio)",
"Interface para Android™",
"Compatível com aplicativo PIONEER SMART SYNC",
"EQ 13-bandas / EQ Gráfico 31-bandas (Pioneer Smart Sync)",
"Função Karaoke (Vocal Cancel)",
        ]
    },

    "MVHS235BT": {
        nome: "Media Player MVHS235BT - Pioneer",
        codigo: "1919.530.0331",
        descricao: "Media Receiver com Bluetooth, USB, Rádio FM, EQ 5-bandas, Bass Bost e Interface SWC.",
        marca: "Pioneer",
        categoria: "Media Player",
        imagem: "./img/MVHS235BT_1.png",
        caracteristicas: [ "Bluetooth para Ligações Hands-free e Streaming de Áudio",
"Entrada USB",
"Rádio FM",
"Equalizador de 5-bandas",
"Função Bass Boost (Reforço de Graves)",
"1 Pares de Saídas RCA Pré-amplificadas (2V)",
"Entrada para Comando de Volante",
        ]
    },

    //Auto Falantes e Subwoofers

    "TS1360BR": {
        nome: "Auto-Falante TS1360BR - Pioneer",
        codigo: "1919.521.0246",
        descricao: "Alto-falante de 5 polegadas, com RMS 50 W de potência e tweeter piezoelétrico.",
        marca: "Pioneer",
        categoria: "Auto-Falante",
        imagem: "./img/TS1360BR_1.png",
        caracteristicas: [ "Woofer com cone de IMPP (Polipropileno moldado por injeção)",
"Bobina de voz resistente ao calor",
"Tweeter piezoelétrico de Ø11 mm em PET",
"Suspensão boleada",
"Midrange com cone de filme de Ø30 mm",
"Vendido em par",
        ]
    },
    
    "TS1390BR": {
        nome: "Auto-Falante TS1390BR - Pioneer",
        codigo: "1919.521.0247",
        descricao: "Alto-falante triaxial de 5 polegadas com RMS 60 W de potência e conjunto magnético de neodímio.",
        marca: "Pioneer",
        categoria: "Auto-Falante",
        imagem: "./img/TS1390BR_1.png",
        caracteristicas: ["Woofer com cone de IMPP (Polipropileno moldado por injeção)",
"Suspensão boleada",
"Tweeter piezoelétrico de Ø11 mm em PET",
"Midrange com conjunto magnético de neodímio",
"Midrange de Ø30 mm com diafragma de policarbonato moldado",
"Bobina de voz resistente ao calor",
"Vendido em Par",
        ]
    },

     "TS1760BR": {
        nome: "Auto-Falante TS1760BR - Pioneer",
        codigo: "1919.521.0248",
        descricao: "Alto-falante de 6 polegadas com potência RMS 50 W e tweeter piezoelétrico.",
        marca: "Pioneer",
        categoria: "Auto-Falante",
        imagem: "./img/TS1760BR_1.png",
        caracteristicas: ["Midrange com cone de filme de Ø30 mm",
"Woofer com cone de IMPP (Polipropileno moldado por injeção)",
"Bobina de voz resistente ao calor",
"Tweeter piezoelétrico de Ø11 mm em PET",
"Suspensão boleada",
"Vendido em par",
        ]
    },

    "TS1790BR": {
        nome: "Auto-Falante TS1790BR - Pioneer",
        codigo: "1919.521.0251",
        descricao: "Alto-falante triaxial de 6 polegadas, com potência RMS 60 W e conjunto magnético de neodímio.",
        marca: "Pioneer",
        categoria: "Auto-Falante",
        imagem: "./img/TS1790BR_1.png",
        caracteristicas: ["Woofer com cone de IMPP (Polipropileno moldado por injeção)",
"Suspensão boleada",
"Bobina de voz resistente ao calor",
"Midrange de Ø30 mm com diafragma de policarbonato moldado",
"Midrange com conjunto magnético de neodímio",
"Tweeter piezoelétrico de Ø11 mm em PET",
"Vendido em Par",
        ]
    },

    "TS6960BR": {
        nome: "Auto-Falante TS6960BR - Pioneer",
        codigo: "1919.521.0252",
        descricao: "Alto-falante quadriaxial 6x9 polegadas – RMS 100 W.",
        marca: "Pioneer",
        categoria: "Auto-Falante",
        imagem: "./img/TS6960BR_1.png",
        caracteristicas: ["Woofer com cone de IMPP (Polipropileno moldado por injeção)",
"Suspensão feita com espuma",
"Bobina em alumínio",
"Midrange com cone de filme de Ø50 mm",
"Tweeter piezoelétrico de Ø29 mm em PET",
"Supertweeter piezoelétrico de PET de Ø12 mm",
"Vendido em par",
        ]
    },

      "TS6990BR": {
        nome: "Auto-Falante TS6990BR - Pioneer",
        codigo: "1919.521.0253",
        descricao: "Alto-falante quadriaxial 6x9 polegadas – RMS 150 W.",
        marca: "Pioneer",
        categoria: "Auto-Falante",
        imagem: "./img/TS6990BR_1.png",
        caracteristicas: ["Woofer com cone de IMPP (Polipropileno moldado por injeção)",
"Suspensão emborrachada",
"Bobina em alumínio",
"Mid-range com cone de filme de Ø50 mm",
"Tweeter piezoelétrico de Ø29 mm em PET",
"Supertweeter piezoelétrico de Ø12 mm em PET",
"Vendido em par",
        ]
    },

     "TS6990BR": {
        nome: "Auto-Falante TS6990BR - Pioneer",
        codigo: "1919.521.0253",
        descricao: "Alto-falante quadriaxial 6x9 polegadas – RMS 150 W.",
        marca: "Pioneer",
        categoria: "Auto-Falante",
        imagem: "./img/TS6990BR_1.png",
        caracteristicas: ["Woofer com cone de IMPP (Polipropileno moldado por injeção)",
"Suspensão emborrachada",
"Bobina em alumínio",
"Mid-range com cone de filme de Ø50 mm",
"Tweeter piezoelétrico de Ø29 mm em PET",
"Supertweeter piezoelétrico de Ø12 mm em PET",
"Vendido em par",
        ]
    },

     "TSC1790BR": {
        nome: "Auto-Falante TSC1790BR - Pioneer",
        codigo: "1919.521.0309",
        descricao: "Uma nova experiência em termos de som.",
        marca: "Pioneer",
        categoria: "Auto-Falante",
        imagem: "./img/TS6990BR_1.png",
        caracteristicas: ["Woofer com cone de IMPP (Polipropileno moldado por injeção)",
"Suspensão emborrachada",
"Bobina em alumínio",
"Mid-range com cone de filme de Ø50 mm",
"Tweeter piezoelétrico de Ø29 mm em PET",
"Supertweeter piezoelétrico de Ø12 mm em PET",
"Vendido em par",
        ]
    },
};


//colocar EAN